<a href="https://colab.research.google.com/github/zi0-hand/data-mining-project/blob/main/src/preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 전처리

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import os
os.chdir('/content/drive/MyDrive/yogiyo-project')

In [5]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import itertools
import io
from functools import reduce

#import os
#os.chdir('C:/Users/sgsgk/Documents/요기요 프로젝트/review data')

df = pd.read_csv('Total row data.csv', encoding= 'cp949')

In [6]:
df.head()

,Unnamed: 0,Address,Address_Road,Restaurant,UserID,Menu,Review,Final,Taste,Quantity,...,Date,Week,WN,Year,WeekNum,Day,Final P,Taste P,Quan P,Delivery P
0,0,강남구,서울특별시 강남구 도곡로 193,1인가득밥상-강남점,-h**님,"제육두루치기쌈밥（1人）/1,스팸구이 /1",배달 빠르고 엄청 맛있는데 스팸 두조각이 너무 얇아요ㅜ 3천원 주고 추가했는데 두께...,4.0,5,4,...,2020-02-27,9,9,2020,202009,Thu,1,0,1,0
1,1,강남구,서울특별시 강남구 도곡로 193,1인가득밥상-강남점,mj**님,"제육두루치기쌈밥（1人）/1,콜라 500mL/1",와 어떻게 배달이 15분만에 와요..?? ㄷㄷ 맛있어요 양도 많고 가성비 굿굿 또 ...,5.0,5,5,...,2020-02-27,9,9,2020,202009,Thu,0,0,0,0
2,2,강남구,서울특별시 강남구 도곡로 193,1인가득밥상-강남점,na**님,"부대찌개/1,돼지갈비구이쌈밥/3,생삼겹살구이쌈밥（1人）/2,계란후라이（2개）/3",양도많고 맛있어요 잘먹었습니다~!,5.0,5,5,...,2020-02-27,9,9,2020,202009,Thu,0,0,0,1
3,3,강남구,서울특별시 강남구 도곡로 193,1인가득밥상-강남점,yc**님,"1인특별 닭도리/1,생삼겹살구이쌈밥（1人）/2",맛도 별로 양도 별로였어요. 요즘 뜨는 맛집이라길래 믿고 시켰는데 주작인가 싶을 정...,1.0,1,1,...,2020-02-27,9,9,2020,202009,Thu,1,1,1,1
4,4,강남구,서울특별시 강남구 도곡로 193,1인가득밥상-강남점,sk**님,생삼겹살구이쌈밥（1人）/1,굿.,4.0,4,4,...,2020-02-27,9,9,2020,202009,Thu,1,1,1,1

In [7]:
df['Restaurant'].value_counts()
# 가장 리뷰가 많은 가게는 '1인가득밥상-강남점'

1인가득밥상-강남점          8082
혼밥혼술                7662
셰플리-셰프의건강한한끼(강남)    7469
멕시카나-봉천행복점          7428
셰플리-셰프의건강한한끼(관악)    7117
                    ...
야꼬닭바베큐-신림점           348
안심탕수육                247
1인밥줘                  50
가츠                    36
버거킹-까치산역점              9
Name: Restaurant, Length: 238, dtype: int64

In [8]:
# '1인가득밥상-강남점'을 기준으로 메뉴 살펴보기

df_menu_num = df[df['Restaurant']=='1인가득밥상-강남점']
df_menu_cont = df_menu_num['Menu'].value_counts().to_frame()
df_menu_cont[df_menu_cont['Menu']>30]

                         Menu
생삼겹살구이쌈밥（1人）/1            829
1인특별 닭도리/1                444
제육두루치기쌈밥（1人）/1            354
닭갈비두루치기쌈밥（1人）/1           316
돼지갈비구이쌈밥（1人）/1            277
오삼두루치기쌈밥（1人）/1            141
부대찌개/1,계란후라이（2개）/1        131
제육두루치기/1,계란후라이（2개）/1      120
돼지김치찌개/1,계란후라이（2개）/1      109
돼지갈비구이쌈밥/1                 97
돼지김치찌개/1,스팸구이 /1           78
돼지김치찌개/1,제육두루치기/1          63
돼지김치찌개/1,생삼겹살구이쌈밥（1人）/1    58
오삼두루치기/1,계란후라이（2개）/1       51
해물순두부찌개/1,계란후라이（2개）/1      49
세트2（돼지갈비＋물냉면 1인）/1         49
해물순두부찌개/1,제육두루치기/1         49
부대찌개/1,제육두루치기/1            47
부대찌개/1,공기밥 /2              44
제육두루치기/1,스팸구이 /1           43
제육덮밥/1,주먹밥 /1              43
부대찌개/1,소세지구이/1             40
제육두루치기/1(추가 선택(쌈 추가))      37
세트1（삼겹살＋물냉면 1인）/1          34
1인특별 닭도리/1,공기밥 /1          31

In [9]:
# 1개의 메뉴만을 시킨 리뷰 추출하기 (/ 하나당 메뉴하나니까)

df_menu_num['menu_count'] = df_menu_num.Menu.str.count('/')

In [10]:
df_menu_num_1 = df_menu_num[df_menu_num['menu_count']==1]
#df_menu_num_1['Menu'].value_counts()

df_menu_count = df_menu_num_1['Menu'].value_counts().to_frame()
df_menu_count[df_menu_count['Menu']>2]

                               Menu
생삼겹살구이쌈밥（1人）/1                  829
1인특별 닭도리/1                      444
제육두루치기쌈밥（1人）/1                  354
닭갈비두루치기쌈밥（1人）/1                 316
돼지갈비구이쌈밥（1人）/1                  277
오삼두루치기쌈밥（1人）/1                  141
돼지갈비구이쌈밥/1                       97
세트2（돼지갈비＋물냉면 1인）/1               49
제육두루치기/1(추가 선택(쌈 추가))            37
세트1（삼겹살＋물냉면 1인）/1                34
생삼겹살구이쌈밥（1人）/2                   30
제육두루치기/2                         26
오징어두루치기쌈밥（1人）/1                  26
부대전골/1(전골메뉴 사이즈 선택(中))           17
삼겹살구이쌈밥/1                        14
돼지갈비구이 /1                        14
제육두루치기쌈밥/1(두루치기쌈밥 사이즈 선택(中))     11
부대찌개/2                            9
돼지김치찌개/2                          7
불고기전골/1(전골메뉴 사이즈 선택(中))           7
1인특별 닭도리/2                        7
돼지갈비구이쌈밥/1(구이쌈밥 사이즈 선택(中))        6
생삼겹살구이쌈밥/1(구이쌈밥 사이즈 선택(中))        6
오삼두루치기/1(추가 선택(쌈 추가))             6
삼겹살구이 /1                          6
제육덮밥/2                            6
해물순두부찌개/2                         6
돼지목살구이쌈밥（1人）/1                    6
호야특별닭도리/1(닭도리탕메뉴 사이즈 선택(小))       6
돼지갈비구이쌈밥/2                        5
생삼겹살구이쌈밥/1(구이쌈밥 사이즈 선택(大))        5
순살호야특별닭도 /1(닭도리탕메뉴 사이즈 선택(小))     5
돼지갈비구이쌈밥（1人）/2                    5
스팸고추장전골/1(전골메뉴 사이즈 선택(中))         4
물냉면/2                             4
제육두루치기쌈밥（1人）/2                    4
돼지김치찌개/1                          3
제육두루치기쌈밥/1(두루치기쌈밥 사이즈 선택(大))      3
돼지김치전골/1(전골메뉴 사이즈 선택(中))          3
오삼두루치기쌈밥/1(두루치기쌈밥 사이즈 선택(中))      3
해물순두부전골/1(전골메뉴 사이즈 선택(中))         3
제육두루치기/3                          3
오징어두루치기/1(추가 선택(쌈 추가))            3

In [11]:
df_menu_num_1.columns

Index(['Unnamed: 0', 'Address', 'Address_Road', 'Restaurant', 'UserID', 'Menu',
       'Review', 'Final', 'Taste', 'Quantity', 'Delivery', 'Date', 'Week',
       'WN', 'Year', 'WeekNum', 'Day', 'Final P', 'Taste P', 'Quan P',
       'Delivery P', 'menu_count'],
      dtype='object')

In [12]:
col = ['Restaurant', 'Menu', 'Final', 'Taste', 'Quantity', 'Delivery', 'Final P', 'Taste P', 'Quan P', 'Delivery P']

In [13]:
df_menu_num_1

,Unnamed: 0,Address,Address_Road,Restaurant,UserID,Menu,Review,Final,Taste,Quantity,...,Week,WN,Year,WeekNum,Day,Final P,Taste P,Quan P,Delivery P,menu_count
4,4,강남구,서울특별시 강남구 도곡로 193,1인가득밥상-강남점,sk**님,생삼겹살구이쌈밥（1人）/1,굿.,4.0,4,4,...,9,9,2020,202009,Thu,1,1,1,1,1
6,6,강남구,서울특별시 강남구 도곡로 193,1인가득밥상-강남점,sa**님,생삼겹살구이쌈밥（1人）/1,적당히 맛있었습니다 감사합니다,4.0,4,4,...,9,9,2020,202009,Wed,1,1,1,1,1
8,8,강남구,서울특별시 강남구 도곡로 193,1인가득밥상-강남점,si**님,제육두루치기쌈밥（1人）/1,양도많고 맛있어서 매번시켜먹게되네요,5.0,5,5,...,9,9,2020,202009,Wed,0,0,0,1,1
10,10,강남구,서울특별시 강남구 도곡로 193,1인가득밥상-강남점,yj**님,생삼겹살구이쌈밥（1人）/1,배갈시감 70분넘고 고기는 재활용인지 다타고 양심어디,1.0,1,1,...,9,9,2020,202009,Wed,1,1,1,1,1
12,12,강남구,서울특별시 강남구 도곡로 193,1인가득밥상-강남점,wi**님,1인특별 닭도리/1,오랜만에 먹었는대 맛있어요,5.0,5,5,...,9,9,2020,202009,Wed,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8071,8071,강남구,서울특별시 강남구 도곡로 193,1인가득밥상-강남점,ko**님,돼지목살구이쌈밥（1人）/1,맛도 괜찮고 양이 조금 적지만 맛나네여,5.0,5,5,...,39,39,2017,201739,Thu,0,0,0,0,1
8073,8073,강남구,서울특별시 강남구 도곡로 193,1인가득밥상-강남점,ky**님,생삼겹살구이쌈밥（1人）/1,무난하네용ㅎㅎ 괜찮았어요,4.0,4,4,...,39,39,2017,201739,Thu,1,1,1,0,1
8079,8079,강남구,서울특별시 강남구 도곡로 193,1인가득밥상-강남점,mi**님,오징어두루치기쌈밥（1人）/1,반찬 많이 달라고 하니 정말 많이 가져다주셨어요~ 그리고 맛도 있고 양도 많고 자주...,4.0,4,4,...,39,39,2017,201739,Wed,1,1,1,1,1
8080,8080,강남구,서울특별시 강남구 도곡로 193,1인가득밥상-강남점,po**님,돼지목살구이/1,"음 뭐랄까, 그냥 맛없었어요. 전부.",1.0,1,1,...,39,39,2017,201739,Tue,1,1,1,1,1
8081,8081,강남구,서울특별시 강남구 도곡로 193,1인가득밥상-강남점,dy**님,생삼겹살구이쌈밥（1人）/1,맛났어요 가격대비 참조아요,5.0,5,5,...,39,39,2017,201739,Tue,0,0,0,0,1

In [14]:
# 일단 수량 고려하지 않고 계산

df_new = df_menu_num_1[['Menu', 'Final P']]
menu_satis = df_new[df_new['Final P']==1]
menu_satis_count = menu_satis['Menu'].value_counts().to_frame()
menu_satis_count.rename(columns={'Menu':'satis'}, inplace=True)
df_merge = pd.merge(df_menu_count, menu_satis_count, left_index=True, right_index=True, how='outer')
df_merge = df_merge.fillna(0)

In [15]:
df_menu_num_1.shape[0]

2933

In [16]:
#@title 전체 평점에 대한 확률 계산값

total = df_menu_num_1.shape[0]
satis_num = menu_satis.shape[0] # 만족한 개수
df_merge['menu_order_per'] = df_merge['Menu'] / total
df_merge['satis_per'] = df_merge['satis'] / total
df_merge['satis_menu_per'] = df_merge['satis_per'] / df_merge['menu_order_per']
# df_merge['satis_menu_per_new'] = (df_merge['satis'] / satis_num) * (satis_num / total) / df_merge['menu_order_per'] # 식 검산 
df_merge.sort_values(by='Menu' ,ascending=False).head(20) # 정렬

,Menu,satis,menu_order_per,satis_per,satis_menu_per
생삼겹살구이쌈밥（1人）/1,829,237.0,0.282646,0.080805,0.285887
1인특별 닭도리/1,444,175.0,0.151381,0.059666,0.394144
제육두루치기쌈밥（1人）/1,354,90.0,0.120696,0.030685,0.254237
닭갈비두루치기쌈밥（1人）/1,316,90.0,0.107740,0.030685,0.284810
돼지갈비구이쌈밥（1人）/1,277,85.0,0.094443,0.028981,0.306859
오삼두루치기쌈밥（1人）/1,141,37.0,0.048074,0.012615,0.262411
돼지갈비구이쌈밥/1,97,17.0,0.033072,0.005796,0.175258
세트2（돼지갈비＋물냉면 1인）/1,49,22.0,0.016706,0.007501,0.448980
제육두루치기/1(추가 선택(쌈 추가)),37,13.0,0.012615,0.004432,0.351351
세트1（삼겹살＋물냉면 1인）/1,34,19.0,0.011592,0.006478,0.558824
생삼겹살구이쌈밥（1人）/2,30,11.0,0.010228,0.003750,0.366667
제육두루치기/2,26,4.0,0.008865,0.001364,0.153846
오징어두루치기쌈밥（1人）/1,26,8.0,0.008865,0.002728,0.307692
부대전골/1(전골메뉴 사이즈 선택(中)),17,4.0,0.005796,0.001364,0.235294
돼지갈비구이 /1,14,10.0,0.004773,0.003409,0.714286
삼겹살구이쌈밥/1,14,1.0,0.004773,0.000341,0.071429
제육두루치기쌈밥/1(두루치기쌈밥 사이즈 선택(中)),11,5.0,0.003750,0.001705,0.454545
부대찌개/2,9,1.0,0.003069,0.000341,0.111111
불고기전골/1(전골메뉴 사이즈 선택(中)),7,1.0,0.002387,0.000341,0.142857
돼지김치찌개/2,7,0.0,0.002387,0.000000,0.000000

In [17]:
fianl_num = df_menu_num_1[df_menu_num_1['Final P']==1].shape[0]
taste_num = df_menu_num_1[df_menu_num_1['Taste P']==1].shape[0]
quan_num = df_menu_num_1[df_menu_num_1['Quan P']==1].shape[0]
deli_num = df_menu_num_1[df_menu_num_1['Delivery P']==1].shape[0]


fianl_satis = df_menu_num_1[df_menu_num_1['Final P']==1]
taste_satis = df_menu_num_1[df_menu_num_1['Taste P']==1]
quan_satis = df_menu_num_1[df_menu_num_1['Quan P']==1]
deli_satis = df_menu_num_1[df_menu_num_1['Delivery P']==1]

fianl_satis_count = fianl_satis['Menu'].value_counts().to_frame()
taste_satis_count = taste_satis['Menu'].value_counts().to_frame()
quan_satis_count = quan_satis['Menu'].value_counts().to_frame()
deli_satis_count = deli_satis['Menu'].value_counts().to_frame()

fianl_satis_count.rename(columns={'Menu':'final'}, inplace=True)
taste_satis_count.rename(columns={'Menu':'taste'}, inplace=True)
quan_satis_count.rename(columns={'Menu':'quan'}, inplace=True)
deli_satis_count.rename(columns={'Menu':'deli'}, inplace=True)


lst = [df_menu_count, fianl_satis_count, taste_satis_count, quan_satis_count, deli_satis_count] 
lst_merge = reduce(lambda left, right: pd.merge(left, right, left_index=True, right_index=True, how='outer'), lst).fillna(0)

lst_merge['final_per'] = lst_merge['final'] / lst_merge['Menu']
lst_merge['taste_per'] = lst_merge['taste'] / lst_merge['Menu']
lst_merge['quan_per'] = lst_merge['quan'] / lst_merge['Menu']
lst_merge['deli_per'] = lst_merge['deli'] / lst_merge['Menu']

In [18]:
#@title 부분 평점에 대한 확률 계산값

lst_merge.sort_values(by='Menu' ,ascending=False).round(2).head(20)

,Menu,final,taste,quan,deli,final_per,taste_per,quan_per,deli_per
생삼겹살구이쌈밥（1人）/1,829,237.0,248.0,240.0,243.0,0.29,0.30,0.29,0.29
1인특별 닭도리/1,444,175.0,188.0,174.0,169.0,0.39,0.42,0.39,0.38
제육두루치기쌈밥（1人）/1,354,90.0,103.0,86.0,102.0,0.25,0.29,0.24,0.29
닭갈비두루치기쌈밥（1人）/1,316,90.0,94.0,87.0,96.0,0.28,0.30,0.28,0.30
돼지갈비구이쌈밥（1人）/1,277,85.0,91.0,84.0,81.0,0.31,0.33,0.30,0.29
오삼두루치기쌈밥（1人）/1,141,37.0,37.0,30.0,37.0,0.26,0.26,0.21,0.26
돼지갈비구이쌈밥/1,97,17.0,22.0,16.0,22.0,0.18,0.23,0.16,0.23
세트2（돼지갈비＋물냉면 1인）/1,49,22.0,23.0,17.0,19.0,0.45,0.47,0.35,0.39
제육두루치기/1(추가 선택(쌈 추가)),37,13.0,16.0,12.0,12.0,0.35,0.43,0.32,0.32
세트1（삼겹살＋물냉면 1인）/1,34,19.0,18.0,14.0,14.0,0.56,0.53,0.41,0.41
생삼겹살구이쌈밥（1人）/2,30,11.0,13.0,12.0,12.0,0.37,0.43,0.40,0.40
제육두루치기/2,26,4.0,3.0,4.0,4.0,0.15,0.12,0.15,0.15
오징어두루치기쌈밥（1人）/1,26,8.0,10.0,5.0,7.0,0.31,0.38,0.19,0.27
부대전골/1(전골메뉴 사이즈 선택(中)),17,4.0,4.0,4.0,1.0,0.24,0.24,0.24,0.06
돼지갈비구이 /1,14,10.0,11.0,10.0,7.0,0.71,0.79,0.71,0.50
삼겹살구이쌈밥/1,14,1.0,2.0,3.0,1.0,0.07,0.14,0.21,0.07
제육두루치기쌈밥/1(두루치기쌈밥 사이즈 선택(中)),11,5.0,5.0,4.0,5.0,0.45,0.45,0.36,0.45
부대찌개/2,9,1.0,1.0,0.0,1.0,0.11,0.11,0.00,0.11
불고기전골/1(전골메뉴 사이즈 선택(中)),7,1.0,2.0,1.0,1.0,0.14,0.29,0.14,0.14
돼지김치찌개/2,7,0.0,2.0,2.0,2.0,0.00,0.29,0.29,0.29

# 여기서 드는 의문
1. 사이즈를 고려할 것인가?
2. 주문 수량을 고려할 것인가?
3. 그 뺀 것은 계산에서도 빼는가?
4. 주문 횟수가 적은 것은 어떻게 고려할 것 인가?
5. 베이지안을 써서 구하는 것과 그냥 통계(별점으로)로 구한 것의 차이는 무엇인가?
6. 주문횟수가 많을수록 오히려 별점 평점은 낮은 경향을 보임, 이런 경우 별점이 정말 만족도를 의미하는게 맞을까?